### ISSUE TITLE
Unified design process

### ISSUE THREAD

**Issue by mishelashala** [ZuraGuerra/wecamefrom.space#2]
If you wanna build a blog you need to define the next things:
1. [ ] Content strategy
2. [ ] Style guide (no more fucking bootstrap)
3. [ ] Structure
4. [ ] Work fucking flow

**Comment by mishelashala** [comment]
# Content Strategy.

Every site has at least this three components.
1. header
2. body
3. footer

## Header

In the header you need to put your blog's name or a description as a heading title.
Optionally if your heading title is your blog's name you can put a sub heading title showing the slogan or a phrase that describes your site.
'Cuz **#original**

## Body

All your stuff :v

## Footer

In the footer you put all the data related to your site: contact links, legal, about, etc.

## Goals:

**Header**
1. [ ] Title (or description)
2. [ ] Slogan (optional)

**Footer**
1. [ ] Social links

**Comment by ZuraGuerra** [comment]
You don't understand my _artistic_ vision for this.

**Comment by mishelashala** [comment]
And I don't give a fuck 'bout it.
